// @ts-check

/**
 * Sidebar definition for the Market Maker documentation set.
 * Uses simple autogenerated sidebar from the folder structure.
 *
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  marketMakerSidebar: [{ type: "autogenerated", dirName: "." }],
};

export default sidebars;
